apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-demo
  namespace: default
data:
  data.1: hello
  data.2: world
  config: |
    proprety.1=value-1
    proprety.2=value-2
    proprety.3=value-3