apiVersion: v1
kind: Pod
metadata:
  name: secret2-pod
  namespace: default
spec:
  volumes:
  - name: secrets
    secret:
      secretName: mysecret
  containers:
  - name: secret2
    image: busybox
    command: ["/bin/sh", "-c", "ls /etc/secrets"]
    volumeMounts:
    - name: secrets
      mountPath: /etc/secrets
    