apiVersion: v1
kind: Pod
metadata:
  name: secret1-pod
  namespace: default
spec:
  containers:
  - name: secret1
    image: busybox
    command: ["/bin/sh", "-c", "env"]
    env:
    - name: USERNAME
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: username
    - name: PASSWORD
      valueFrom:
        secretKeyRef:
          name: mysecret
          key: password
    envFrom:
    - secretRef:
        name: mysecret