apiVersion: v1
kind: Pod
metadata:
  name: testcm4-pod
  namespace: default
spec:
  volumes:
  - name: config-volume
    configMap:
      name: cm-demo1
      items:
      - key: mysql.conf
        path: path/to/mysql.conf 
  containers:
  - name: testcm4
    image: busybox
    command: ["/bin/sh", "-c", "cat /etc/config/path/to/msyql.conf;sleep 60"]
    volumeMounts:
    - name: config-volume
      mountPath: /etc/config
    